apiVersion: v1
kind: Secret
metadata:
  name: redis-api-secrets
  namespace: renovai-api
type: Opaque
stringData:
  REDIS_URL: "rediss://default:SENHA@HOST:PORTA/0"
  DATABASE_URL: "postgresql://USUARIO:SENHA@HOST:5432/renovai?sslmode=require"
